Module2 task1
htmlacademy-adaptive/1690249-cat-energy-22 pull request #2
Opened 2021-03-30 20:03 UTC by ikonnikoweb

2021-03-30 22:26 UTC, Zakamsky requested changes
В целом вижу неплохое понимание БЭМ, старательно разбито на блоки все, есть пара помарок, но сейчас все поправим и кажется все встанет на свои места, т.к. ошибки не системные... Хотя кажется есть путаница с миксинами. Давай в чате обсудим.

2021-03-30 22:26 UTC, Zakamsky commented on source/index.html
> +          <div class="result-slider">
Строго говоря тут все корреткно, но кажется немного странным, давай порассуждаем.
получается что `result-list` `result-price` и `result-slider`
полностью. независимые блоки, и у каждого будет свой файл стилей, и если с `result-slider` все очевидно, то с `result-price` возникает вопрос - действительно ли он такой уж независимый? Я бы предложил объединить список с параграфом в общем диве, он нам еще и пригодиться позже для стилизации, что бы рядом два блока расположить флексами. И этот див назначить блоком, элементами которого и будут  список и парагрф.
Это можно будет переосмыслить в момент стилизации уже, или сейчас если будут еще ошибки...

2021-03-30 22:26 UTC, Zakamsky commented on source/index.html
> +            </div>
А вот тут ц нас что то странное...
это вложенность блока `result-slider`
картинки не похожи на самостоятельные блоки, это части чего то большего, кроме того у них как бы модификаторы, но с нарушенным синтаксисом...
а ниже лежат элементы отсутствующего блока `result`
Предполагаю что все это задумывалось как элементы блока `result-slider`
Если да, то стоит поправить:
`result-slider__img result-slider__img--before`
`result-slider__scale-wrapper` и так далее...
Во всяком случае использовать элементы без блока мы не можем. Это нарушение критерия Б5 т.к. это ошибка в методологии.

2021-03-30 22:26 UTC, Zakamsky commented on source/index.html
> +            <a href="#">
Возможно ты имел ввиду миксин, но потерялся класс самого блока `socials-list` есть такой элемент у блока `page-footer` есть его элементы `socials-list__item` а самого `socials-list` нет...

2021-03-30 22:26 UTC, Zakamsky commented on source/index.html
> +          <a class="copy__logo" href="https://htmlacademy.ru/intensive/adaptive">
тут очевидно так же пропущен блок `copy` .

2021-03-31 08:27 UTC, ikonnikoweb commented on source/index.html
> +          <div class="result-slider">
тут все понял, единственное немного в ступор загоняет именование блоков/элементов  глубокой вложенности... Вот у меня блок `.result `> в нем элементы `.result__list` и `.result__price` ... В  `.result__list` 2 элемента и как их называть правильно по БЭМ, тут ступор, то ли это `.result__item` или может .result__list--item , но вроде это же не модификатор. а дальше там вложены `dt` и `dd` и они тоже явно не модификаторы что бы им там класс с дефисами давать, и  короче на моменте со вложенностью я плыву. надо что то читать или лекцию пересматривать.

2021-03-31 09:00 UTC, ikonnikoweb commented on source/index.html
> +            </div>
мммм...так продолжаю размышления свои...вот тут опять же всё понятно с элементами `.result-slider__img` и `.result-slider__scale-wrapper` эту ошибку вроде понял, но дальше у `.result-slider__scale-wrapper` вложены его элементы, я правильно понимаю, что надо сделать `.result-slider__scale-wrapper` блоком, для этого дать ему еще один класс, например `.scale-wrapper` ? и уже всё что вложено в него будет элементами блока `.scale-wrapper`, т.е. `.scale-wrapper__button` `.scale-wrapper__scale`

2021-03-31 09:07 UTC, ikonnikoweb commented on source/index.html
> +          <a class="copy__logo" href="https://htmlacademy.ru/intensive/adaptive">
та же басня, что и со списком .socials-list?

2021-03-31 16:07 UTC, Zakamsky commented on source/index.html
> +          <div class="result-slider">
Вложенность продолжает оставаться элементами блока, т.е. `.result__item` это верный подход.
модификаторы кончено нужны если один одинаковый элемент отличается от других таких же.
в общем это все элементы до тех пор пока мы не положим внутрь еще какой то блок, как `.result` лежит внутри `.example`

2021-03-31 16:11 UTC, Zakamsky commented on source/index.html
> +            <a href="#">
Да! Бинго! Это и есть миксин. мы смешали в одном элементе штмл - элемент и блок БЭМ.
хотя могли бы просто положить список в див с классом элемента, но это лишний див будет лучше миксин.

2021-03-31 16:11 UTC, Zakamsky commented on source/index.html
> +          <a class="copy__logo" href="https://htmlacademy.ru/intensive/adaptive">
да.

2021-03-31 16:12 UTC, merged